# Generated by Django 2.2.3 on 2019-12-03 18:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('birth_date', models.DateField(null=True)),
                ('death_date', models.DateField(null=True)),
                ('bio', models.TextField(null=True)),
                ('nationality', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('coverimagepath', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('bio', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_dt', models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 4, 0, 39, 26, 454666))),
                ('return_dt', models.DateTimeField(blank=True, default=None)),
                ('issue_cmnt', models.TextField(null=True)),
                ('return_cmnt', models.TextField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Member')),
            ],
        ),
    ]
